name: Build and Deploy Code

on: [push, pull_request]

jobs:
  job1:
    environment:
      name: testing
    env:
      DB_USER: ${{secrets.DATABASE_USERNAME}}
      DB_PASSWORD: ${{secrets.DATABASE_PASSWORD}}
      DB_HOST: ${{secrets.DATBASE_HOSTNAME}}
      DB_PORT: ${{secrets.DATABASE_PORT}}
      DB_NAME: ${{secrets.DATABASE_NAME}}
      ENV: local
      SECRET_KEY: ${{secrets.SECRET_KEY}}
      ALGORITHM: ${{secrets.ALGORITHM}}
      ACCESS_TOKEN_EXPIRE_MINUTES: ${{secrets.ACCESS_TOKEN_EXPIRE_MINUTES}}
    
    services:
      postgres:
        image: postgres
        env:
          POSTGRES_PASSWORD: ${{secrets.DATABASE_PASSWORD}}
          POSTGRES_DB: ${{secrets.DATABASE_NAME}}_test
        ports:
          - 5432:5432
        options: >-
           --health-cmd pg_isready
           --health-interval 10s
           --health-timeout 5s
           --health-retries 5
    runs-on: ubuntu-latest
    steps:
      - name: pulling git repo
        uses: actions/checkout@v2
      - name: Debug ENV variables
        run: |
          echo "DB_USER: $DATABASE_USERNAME"
          echo "DB_PASSWORD: $DATABASE_PASSWORD"
          echo "DB_HOST: $DATBASE_HOSTNAME"
          echo "DB_PORT: $DATABASE_PORT"
          echo "DB_NAME: $DATABASE_NAME"
          echo "SECRET_KEY: $SECRET_KEY"
          echo "ALGORITHM: $ALGORITHM"
          echo "ACCESS_TOKEN_EXPIRE_MINUTES: $ACCESS_TOKEN_EXPIRE_MINUTES"
      - name: Install python version 3.10.11
        uses: actions/setup-python@v2
        with:
          python-version: "3.10.11"
      - name: update pip
        run: python -m pip install --upgrade pip
      - name: install all dependencies
        run: pip install -r requirements.txt
      - name: test with pytest
        run: |
          pip install pytest
          pytest -v -s